project_name: sys-agent
dist: .bin
builds:
  - id: sys-agent
    binary: "sys-agent"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    dir: app
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: sys-agent
    name_template: >-
      {{.ProjectName}}_
      {{- .Tag}}_
      {{- if eq .Os "darwin"}}macos
      {{- else if eq .Os "windows"}}win
      {{- else}}{{.Os}}{{end}}_
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386"}}i386
      {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/*
    rlcp: true


brews:
  -
    name: sys-agent
    tap:
      owner: umputun
      name: homebrew-apps
      branch: master
    directory: Formula
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://sys-agent.umputun.dev"
    description: "SysAgent is a simple service reporting server status via HTTP GET request. It is useful for monitoring and debugging purposes, but usually used as a part of some other monitoring system collecting data and serving it."
    license: "MIT"
    extra_install: |
      bash_completion.install "completions/sys-agent.bash" => "sys-agent"
      zsh_completion.install "completions/sys-agent.zsh" => "_sys-agent"
      fish_completion.install "completions/sys-agent.fish" => "sys-agent.fish"

nfpms:
  - id: sys-agent
    package_name: sys-agent
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://sys-agent.umputun.dev
    maintainer: Umputun <umputun@gmail.com>
    description: system status agent
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
    release: 1
    contents:
      - src: sys-agent.service
        dst: /etc/systemd/system/sys-agent.service
      - src: completions/sys-agent.bash
        dst: /usr/share/bash-completion/completions/sys-agent
      - src: completions/sys-agent.zsh
        dst: /usr/share/zsh/vendor-completions/_sys-agent
      - src: completions/sys-agent.fish
        dst: /usr/share/fish/vendor_completions.d/sys-agent.fish

