builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    dir: app
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  -
    id: sys-agent
    package_name: sys-agent
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://github.com/umputun/sys-agent
    maintainer: Umputun <umputun@gmail.com>
    description: system status agent
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1
    contents:
      - src: sys-agent.service
        dst: /etc/systemd/system/sys-agent.service
